# Site settings
title: The Life Electric
description: >- # site description
  A (somewhat) live journal of my move to an electric vehicle, hoping to give others some insight if they want to make the plunge.
lang: en-US
timezone: America/Los_Angeles
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: 
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Nate # author name
  bio: >-
    Computer user, electron abuser.
  username: 
  github: 
  twitter:
  facebook: 
  email: 
  avatar: /assets/img/avatar.png # change with your own avatar

# URL settings
url: "thelifeelectric.us" #
baseurl:
permalink: /:title/
google_analytics: G-C3PF4KEK0E
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec
  - vendor

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
